import { StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "../index.css";
import { PadPanelsOverlay, type Direction, type PadSensor, type PanelRect } from "~/components/PadPanels";
import { useOBS } from "~/lib/useOBS";

// Standalone page loaded directly by OBS's Browser Source (its own CEF
// instance, not the main app window) -- same setup as graph.tsx/sensors.tsx.
// It opens its OWN obs-websocket connection using the "pwd" query param
// (generated by OBSComponentDialog) and listens for the exact same
// {values, thresholds} CustomEvent broadcastToOBS() already sends every
// tick from Dashboard.tsx. No new fields needed on ObsBroadcastPayload --
// "is this panel active" is just value >= threshold, computed here, the
// same logic the itgManiaBridge broadcast already uses.

// Mirrors encodeColorListForUrl/encodeSensorLabelsForUrl in
// OBSComponentDialog.tsx -- colors and labels travel through the URL in
// EXACTLY that format, so the dialog stays the single source of truth for
// how these lists get serialized. Falls back to a plain comma-split for
// values that never went through the encoder (hand-edited URLs).
const decodeColorListFromUrl = (colorsParam: string): string[] =>
	colorsParam.includes(";") ? colorsParam.split(";").map((c) => decodeURIComponent(c)) : colorsParam.split(",");
const decodeSensorLabelsFromUrl = (labelsParam: string): string[] =>
	labelsParam.split(";").map((label) => decodeURIComponent(label));

// Mirrors encodePanelRectsForUrl in OBSComponentDialog.tsx. Format:
// "up:top,left,width,height;down:...;left:...;right:..." (percentages).
// Directions omitted here just fall back to PadPanelsOverlay's own grid
// default, so a hand-edited URL missing a direction (or malformed
// numbers for one) degrades gracefully instead of breaking the page.
const decodePanelRectsFromUrl = (panelRectsParam: string): Partial<Record<Direction, PanelRect>> => {
	const result: Partial<Record<Direction, PanelRect>> = {};
	for (const entry of panelRectsParam.split(";")) {
		const [dir, nums] = entry.split(":");
		if (!dir || !nums) continue;
		const [top, left, width, height] = nums.split(",").map(Number);
		if ([top, left, width, height].some((n) => Number.isNaN(n))) continue;
		result[dir as Direction] = { top, left, width, height };
	}
	return result;
};

const DEFAULT_SENSOR_COLORS = ["#3a7da3", "#d4607c", "#8670d4", "#d49b20", "#459ea0", "#d45478"];
const DEFAULT_SENSOR_LABELS = ["Left", "Down", "Up", "Right", "Up 2", "Down 2"];
// Bundled fallback -- same file the in-app LED Pad Preview tab uses. Make
// sure a copy of pad-background.png also lands in this page's own public
// output (mirroring vite.config.ts's base: "./" so it still resolves once
// OBS loads this over its own local static server / GitHub Pages, same
// reasoning as PAD_BACKGROUND_URL in dashboard_pro.tsx).
const DEFAULT_PAD_IMAGE = "./pad-background.png";

function PadOverlay() {
	const { connect, addCustomEventListener, setAutoConnectEnabled } = useOBS();
	const [imageError, setImageError] = useState(false);
	const [values, setValues] = useState<number[]>([]);
	const [thresholds, setThresholds] = useState<number[]>([]);

	// Query params are static for the lifetime of this page (OBS never
	// navigates it), so read them once rather than re-parsing on every
	// render.
	const params = useMemo(() => new URLSearchParams(window.location.search), []);

	const pwd = params.get("pwd") || "";
	const padImageUrl = params.get("padImage") || DEFAULT_PAD_IMAGE;
	const sensorColors = params.get("colors") ? decodeColorListFromUrl(params.get("colors")!) : DEFAULT_SENSOR_COLORS;
	const sensorLabels = params.get("sensorLabels") ? decodeSensorLabelsFromUrl(params.get("sensorLabels")!) : DEFAULT_SENSOR_LABELS;
	const idleOpacity = params.get("idleOpacity") ? Number(params.get("idleOpacity")) : 0.22;
	const activeOpacity = params.get("activeOpacity") ? Number(params.get("activeOpacity")) : 0.95;
	const glowEnabled = params.get("glow") !== "false";
	const containerBgColor = params.get("containerBgColor") || "rgba(0,0,0,0)";
	const maxWidthPx = params.get("size") ? Number(params.get("size")) : 480;
	const panelRects = params.get("panelRects") ? decodePanelRectsFromUrl(params.get("panelRects")!) : undefined;

	// Connect once on mount. autoConnect handles reconnecting with backoff
	// if obs-websocket restarts or OBS itself relaunches -- same mechanism
	// the main dashboard uses for its own OBS connection, so this overlay
	// doesn't need OBS to be restarted to pick back up.
	useEffect(() => {
		if (!pwd) return;
		setAutoConnectEnabled(true, pwd);
		void connect(pwd);
		// Only pwd should ever change here (it can't, mid-session, but the
		// lint rule doesn't know that) -- connect/setAutoConnectEnabled are
		// re-created every render by useOBS, so including them would just
		// reconnect on every render for no reason.
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [pwd]);

	// Subscribed once -- the underlying OBSWebSocket instance inside
	// useOBS is held in a ref and stays the same across this component's
	// re-renders, so there's no need to re-subscribe when the returned
	// addCustomEventListener function reference changes.
	useEffect(() => {
		const unsubscribe = addCustomEventListener((payload) => {
			if (payload.values) setValues(payload.values);
			if (payload.thresholds) setThresholds(payload.thresholds);
		});
		return unsubscribe;
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	const sensors: PadSensor[] = sensorLabels.map((label, i) => ({
		index: i,
		label,
		color: sensorColors[i % sensorColors.length] || "#ffffff",
	}));

	const isActive = (sensorIndex: number) => {
		const value = values[sensorIndex];
		const threshold = thresholds[sensorIndex];
		if (value === undefined || threshold === undefined) return false;
		return value >= threshold;
	};

	return (
		<div
			style={{
				position: "fixed",
				inset: 0,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
				background: containerBgColor,
				overflow: "hidden",
			}}
		>
			{/* Defensive reset -- OBS Browser Source should be set to
			    "transparent background", but if someone forgets, at least
			    this page itself won't show a white flash or scrollbars. */}
			<style>{`html, body, #root { margin: 0; background: transparent; overflow: hidden; }`}</style>

			<div style={{ position: "relative", width: "100%", maxWidth: maxWidthPx, aspectRatio: "1 / 1" }}>
				{!imageError ? (
					<img
						src={padImageUrl}
						alt="Pad layout"
						draggable={false}
						onError={() => setImageError(true)}
						style={{
							position: "absolute",
							inset: 0,
							width: "100%",
							height: "100%",
							objectFit: "cover",
							userSelect: "none",
							borderRadius: 12,
						}}
					/>
				) : (
					// Keep this quiet on stream -- a missing image shouldn't
					// dump troubleshooting text over someone's live feed.
					// It'll just render as an empty rounded box; the
					// person testing the URL in a regular browser tab will
					// still see the layout is there, just imageless.
					<div style={{ position: "absolute", inset: 0, borderRadius: 12, background: "rgba(0,0,0,0.35)" }} />
				)}

				<PadPanelsOverlay
					sensors={sensors}
					isActive={isActive}
					idleOpacity={idleOpacity}
					activeOpacity={activeOpacity}
					glowEnabled={glowEnabled}
					panelRects={panelRects}
				/>
			</div>
		</div>
	);
}

createRoot(document.getElementById("root")!).render(
	<StrictMode>
		<PadOverlay />
	</StrictMode>,
);
